services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sensorhub
      POSTGRES_PASSWORD: sensorhub
      POSTGRES_DB: sensorhub

    ports: 
      - "5432:5432"

    volumes: 
      - postgres_data:/var/lib/postgresql/data

  api: 
    build: . 
    ports: 
      - "8000:8000"
    environment: 
     DATABASE_URL: postgresql://sensorhub:sensorhub_pass@db:5432/sensorhub
    depends_on:
      - db
volumes:
  postgres_data:
