#  este documento se creo con la necesidad de evaluar el trabajo
#  para el api sugerido por la IA 
[pytest]
addopts = --import-mode=importlib --ignore=semana0 --ignore=semana1 --ignore=semana2
#por problemas de pruebas de test debido a la ubicacion de la app 
#se tuvo que ignorar las demas carpetas para poder evaluar la 
# funcionalidad de la app con ayuda de pytest --cov=app
pythonpath = .